import Head from 'next/head'
import { ConnectButton } from '@rainbow-me/rainbowkit';


export default function AppNav(){





    return(
<>
<Head>
    <title>Taiko NFT bridge</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>


  <nav className=" px-2 sm:px-4 py-2.5 dark:bg-gray-900 fixed w-full z-20 top-0 left-0  dark:border-gray-600">
  <div className="container flex flex-wrap items-center justify-between mx-auto">
  <a href="https://flowbite.com/" className="flex items-center">
      {/* <img src="https://flowbite.com/docs/images/logo.svg" className="h-6 mr-3 sm:h-9" alt="Flowbite Logo"> */}
      <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Taiko-NFT</span>
  </a>
  <div className="flex md:order-2">
  <ConnectButton/>
  </div>

  </div>
</nav>





</>



    );



}